#	$NetBSD$

INCSDIR=	/usr/include/aarch64

# Install thin wrappers that map to existing ARM headers.
INCS=		asm.h \
		byte_swap.h \
		cdefs.h \
		ansi.h \
		int_mwgwtypes.h \
		int_limits.h \
		endian.h \
		endian_machdep.h \
		int_const.h \
		wchar_limits.h \
		bswap.h \
		int_fmtio.h \
		signal.h \
		limits.h \
		param.h \
		elf_machdep.h \
		int_types.h \
		types.h

# Additional machine headers analogous to x86's installed set.
INCS+=	aout_machdep.h \
		bootinfo.h \
		cacheinfo.h \
		cpu.h \
		cpu_extended_state.h \
		cpu_ucode.h \
		cputypes.h \
		cpuvar.h \
		float.h \
		fpu.h \
		ieee.h ieeefp.h \
		intr.h intrdefs.h \
		lock.h \
		math.h mutex.h \
		mtrr.h \
		pio.h \
		pmap.h \
		pmap_pv.h \
		psl.h \
		pte.h \
		rwlock.h \
		specialreg.h \
		sysarch.h \
		trap.h \
		via_padlock.h

.include <bsd.kinc.mk>
